services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - cinema
  backend:
    build:
      context: ./tecno-construcao-cinema-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - cinema
  frontend:
    build:
      context: ./tecno-construcao-cinema-react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - cinema
networks:
  cinema:
    driver: bridge