services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - cinema

  backend:
    build:
      context: ./tecno-construcao-cinema-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db
    networks:
      - cinema

  frontend:
    build:
      context: ./tecno-construcao-cinema-react
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - cinema

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - cinema

networks:
  cinema:
    driver: bridge
